"""
Django settings for APP_CORE project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'arl%1+5u@ni4ix#5o7h5bl@#i87c#zg9#h0ua*90d2znl8hkt6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#@ ================================================================================
#@
#@ ================================================================================

#@ ALLOWED_HOSTS
#@ - set to ['*'] to allow connection from any address in the network
#@
ALLOWED_HOSTS = ['*']


#@ INSTALLED_APPS
#@ - added libraries:
#@   modernrpc, rest_framework, social_django, bootstrap3
#@ - registered apps:
#@   Hello (default)
#@
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- Libraries
    'modernrpc',            # for rpc.py files, xml-json rpc calls & control
    'rest_framework',       # for rest API (JSON, JSONP) used in view
    # --- APPS
    'Hello',
]



#@ MODERNRPC_METHODS_MODULES
#@ - registers Hello.api_rpc
#@
MODERNRPC_METHODS_MODULES = [
        'Hello.api_rpc'
    ]

#@ REST_FRAMEWORK
#@ - default rest framework rendered
REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': (
            'rest_framework_jsonp.renderers.JSONPRenderer',
        ),
    }


#@ LOGIN_URL
#@ - default: set to /login
LOGIN_URL = '/account/login/'

#@ LOGOUT URL
#@ - default: set to /logout
LOGOUT_URL = '/account/logout/'

#@ LOGIN REDIRECT
#@ - after login, go to server root
LOGIN_REDIRECT_URL = '/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#@ ROOT URL CONFIG ---
#@  - set root url file to be in APP_CORE.urls
#@
ROOT_URLCONF = 'APP_CORE.urls'

#@ TEMPLATES CONFIG ---
#@ - sets default template within APP_CORE/templates/
#@ - added OPTIONS.libraries to load APP_CORE.templatetags.tags_project
#@     tags_project.py becomes placeholder for project wide template tags_project
#@ - added OPTIONS.builtin to load tags_builtin.py as builtin template tags
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates',    # look into each app directory
            BASE_DIR+'/APP_CORE/templates', # but also in APP_CORE/templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            # tags registered here can be loaded from all apps within
            # this projects
            'libraries': {
                'tags_project':'APP_CORE.templatetags.tags_project',
            },
            # tags registered here gets baked into django template
            # and are automatically loadeds
            'builtins': [
                'APP_CORE.templatetags.tags_builtin',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'APP_CORE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#@ DATABASES
#@ - changed default to MYSQL backend. change NAME, USER, PASSWORD, HOST, PORT accordingly.
DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.mysql',
        'NAME':'django_hello',
        'USER':'root',
        'PASSWORD':'root',
        'HOST':'localhost',
        'PORT': '',
    },
    # 'theoriginal-default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'), #<- this file is deleted. We don't need this
    # }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

#@ STATIC_URL
#@  - set to default /static
#@
STATIC_URL = '/static/'

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'APP_CORE/static'),
)

#@ STATIC_ROOT
#@  - set to be under APP_CORE/static/
#@
# STATIC_ROOT = os.path.join(BASE_DIR, "APP_CORE/static")

# STATICFILES_FINDERS = (
# 'django.contrib.staticfiles.finders.FileSystemFinder',
# 'django.contrib.staticfiles.finders.AppDirectoriesFinder',
# #'django.contrib.staticfiles.finders.DefaultStorageFinder',
# )
