# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('date_c', models.DateTimeField(auto_now_add=True)),
                ('date_u', models.DateTimeField(auto_now=True)),
                ('isGood', models.BooleanField(default=False)),
            ],
        ),
    ]
