# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
